/// <reference types="cypress" />

describe('Contact us Page functionality ', () => {
    beforeEach(() => {
        Cypress.on('uncaught:exception', err => !err.message.includes('ResizeObserver loop limit exceeded'))

        cy.viewport(1280,720)
        cy.visit('https://pixer-shop.vercel.app/')
        cy.get('[href="/contact-us"]').click()
        cy.url().should('eq',"https://pixer-shop.vercel.app/contact-us")
    })
    it('Submit form without any input', () => {
        cy.contains('Successfully sent your message').should('not.exist')
        cy.get('form').within(($form) => {
            cy.root().submit()
        })
        cy.contains('name is a required field').should('exist')
        cy.contains('email is a required field').should('exist')
        cy.contains('subject is a required field').should('exist')
        cy.contains('description is a required field').should('exist')
        cy.contains('Successfully sent your message').should('not.exist')
    })
    it('Submit form without name', () => {
        cy.contains('Successfully sent your message').should('not.exist')
        cy.get('form').within(($form) => {
            cy.get('input[name="email"]').type('taj@gmail.com')
            cy.get('input[name="subject"]').type('Automation test')
            cy.get('textarea[name="description"]').type('This is for automation')
            cy.root().submit()
        })
        cy.contains('name is a required field').should('exist')
        cy.contains('email is a required field').should('not.exist')
        cy.contains('subject is a required field').should('not.exist')
        cy.contains('description is a required field').should('not.exist')
        cy.contains('Successfully sent your message').should('not.exist')
    })
    it('Submit form without email', () => {
        cy.contains('Successfully sent your message').should('not.exist')
        cy.get('form').within(($form) => {
            cy.get('input[name="name"]').type('demo')
            cy.get('input[name="subject"]').type('Automation test')
            cy.get('textarea[name="description"]').type('This is for automation')
            cy.root().submit()
        })
        cy.contains('name is a required field').should('not.exist')
        cy.contains('email is a required field').should('exist')
        cy.contains('subject is a required field').should('not.exist')
        cy.contains('description is a required field').should('not.exist')
        cy.contains('Successfully sent your message').should('not.exist')
    })
    it('Submit form without subject', () => {
        cy.contains('Successfully sent your message').should('not.exist')
        cy.get('form').within(($form) => {
            cy.get('input[name="name"]').type('demo')
            cy.get('input[name="email"]').type('taj@gmail.com')
            cy.get('textarea[name="description"]').type('This is for automation')
            cy.root().submit()
        })
        cy.contains('name is a required field').should('not.exist')
        cy.contains('email is a required field').should('not.exist')
        cy.contains('subject is a required field').should('exist')
        cy.contains('description is a required field').should('not.exist')
        cy.contains('Successfully sent your message').should('not.exist')
    })
    it('Submit form without descripion', () => {
        cy.contains('Successfully sent your message').should('not.exist')
        cy.get('form').within(($form) => {
            cy.get('input[name="name"]').type('demo')
            cy.get('input[name="email"]').type('taj@gmail.com')
            cy.get('input[name="subject"]').type('Automation test')
            cy.root().submit()
        })
        cy.contains('name is a required field').should('not.exist')
        cy.contains('email is a required field').should('not.exist')
        cy.contains('subject is a required field').should('not.exist')
        cy.contains('description is a required field').should('exist')
        cy.contains('Successfully sent your message').should('not.exist')
    })
    it('Submit contact us form with valid information', () => {
        cy.contains('Successfully sent your message').should('not.exist')
        cy.get('form').within(($form) => {
            cy.get('input[name="name"]').type('demo')
            cy.get('input[name="email"]').type('taj@gmail.com')
            cy.get('input[name="subject"]').type('Automation test')
            cy.get('textarea[name="description"]').type('This is for automation')
            cy.root().submit()
        })
        cy.contains('name is a required field').should('not.exist')
        cy.contains('email is a required field').should('not.exist')
        cy.contains('subject is a required field').should('not.exist')
        cy.contains('description is a required field').should('not.exist')
        cy.contains('Successfully sent your message').should('exist')
    })
})